import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsNotEmpty, IsString, IsOptional, IsBoolean } from 'class-validator';

export class TiktokLoginDto {
  @ApiProperty({
    description: 'The temporary Authorization Code received from TikTok',
    example: 'auth_code_xyz123',
  })
  @IsString()
  @IsNotEmpty()
  code: string;

  @ApiProperty({
    description: 'The exact Redirect URI that was used to obtain the authorization code',
    example: 'http://localhost:3000/auth/tiktok/callback',
  })
  @IsString()
  @IsNotEmpty()
  redirectUri: string;

  @ApiPropertyOptional({
    description: 'Selected role for new user signup (creator or brand)',
    example: 'creator',
    default: 'creator',
  })
  @IsString()
  @IsOptional()
  role?: string;

  @ApiPropertyOptional({
    description: 'The PKCE code verifier generated by the client',
    example: 'some_cryptographically_secure_random_string',
  })
  @IsString()
  @IsOptional()
  codeVerifier?: string;

  @ApiPropertyOptional({
    description: 'Acceptance of terms and conditions',
    example: true,
  })
  @IsBoolean()
  @IsOptional()
  acceptedTerms?: boolean;

  @ApiPropertyOptional({
    description: 'Acceptance of promotional emails',
    example: true,
  })
  @IsBoolean()
  @IsOptional()
  acceptedPromotions?: boolean;
}
